// Generated by diesel_ext (insertable structs)

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
use bigdecimal::BigDecimal;
use chrono::DateTime;
use chrono::offset::Utc;
#[derive(Insertable)]
#[diesel(table_name = carry_over_balances)]
pub struct NewCarryOverBalance<'a> {
    pub debit: BigDecimal,
    pub description: Option<&'a str>,
    pub description2: Option<Vec<&'a str>>,
}

#[derive(Insertable)]
#[diesel(table_name = orders)]
pub struct NewOrder<'a> {
    pub time: NaiveDateTime,
    pub time2: DateTime<Utc>,
    pub json: &'a str,
}